import {Inter} from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFlies from "@/components/FireFlies";
import Image from "next/image";
import Link from "next/link";
import logo from "../../public/logo.png"
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/navigation/Footer";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter"
});


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={clsx(inter.variable, "bg-background text-foreground ")}>
        <Navbar />
        {children}
        <FireFlies/>
        <Footer />
        </body>
        </html>
    );
}
