import {Inter} from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFlies from "@/components/FireFlies";
import Image from "next/image";
import Link from "next/link";
import logo from "../../public/logo.png"

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter"
});


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={clsx(inter.variable, "bg-background text-foreground")}>
        <Link href="/" className="cursor-pointer top-[15px] left-[15px] fixed flex items-center justify-center z-20">
            <Image src={logo} alt='logo' className="w-[45px] h-[40px] mr-4"/>
            <span className="text-white text-sm border-l-[1px] border-white tracking-widest h-full pl-4 uppercase">Oleksii Koba</span>
        </Link>

        {children}
        <FireFlies/>
        </body>
        </html>
    );
}
